
sonar.projectKey=HermesLei_projetos-data-eng
sonar.organization=hermeslei

sonar.projectName=projetos-data-eng
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=.git/**,.github/**,.venv/**,venv/**,**/__pycache__/**,**/*.ipynb